### ISSUE TITLE
Is it possible to implement MATLAB's debuger in vscode?

### ISSUE THREAD

**Issue by zbqhc** [378978764/vscode-matlab-custom-package-plugin#1]

**Comment by sheng-di** [comment]
[aMi](https://github.com/marmottetranquille/aMi) seems to support this, but it only supports linux. You can fork it, but this will take time and it is estimated to be very complicated.

**Comment by zbqhc** [comment]
I happen to be working with Linux. I tried, but it doesn't work properly. Anyway, your plugin program helped me with the Jump-to-definition function.
